/*****************************************************
 * WARNING: this file was generated by -e
 * on Wed Feb 15 18:26:49 2017.
 * Any changes made here will be LOST.
 *****************************************************/
package org.hyperic.sigar;

import java.util.HashMap;
import java.util.Map;

/**
 * Arp sigar class.
 */
public class Arp implements java.io.Serializable {

    private static final long serialVersionUID = 6647L;

    public Arp() { }

    public native void gather(Sigar sigar) throws SigarException;

    /**
     * This method is not intended to be called directly.
     * use Sigar.getArp() instead.
     * @exception SigarException on failure.
     * @see org.hyperic.sigar.Sigar#getArp
     */
    static Arp fetch(Sigar sigar) throws SigarException {
        Arp arp = new Arp();
        arp.gather(sigar);
        return arp;
    }

    String ifname = null;

    /**
     * Get the ifname.<p>
     * Supported Platforms: All.
     * <p>
     * @return ifname
     */
    public String getIfname() { return ifname; }
    String hwaddr = null;

    /**
     * Get the hwaddr.<p>
     * Supported Platforms: All.
     * <p>
     * @return hwaddr
     */
    public String getHwaddr() { return hwaddr; }
    String type = null;

    /**
     * Get the type.<p>
     * Supported Platforms: All.
     * <p>
     * @return type
     */
    public String getType() { return type; }
    String address = null;

    /**
     * Get the address.<p>
     * Supported Platforms: All.
     * <p>
     * @return address
     */
    public String getAddress() { return address; }
    long flags = 0;

    /**
     * Get the flags.<p>
     * Supported Platforms: All.
     * <p>
     * @return flags
     */
    public long getFlags() { return flags; }

    void copyTo(Arp copy) {
        copy.ifname = this.ifname;
        copy.hwaddr = this.hwaddr;
        copy.type = this.type;
        copy.address = this.address;
        copy.flags = this.flags;
    }

    public Map toMap() {
        Map map = new HashMap();
        String strifname = 
            String.valueOf(this.ifname);
        if (!"-1".equals(strifname))
            map.put("Ifname", strifname);
        String strhwaddr = 
            String.valueOf(this.hwaddr);
        if (!"-1".equals(strhwaddr))
            map.put("Hwaddr", strhwaddr);
        String strtype = 
            String.valueOf(this.type);
        if (!"-1".equals(strtype))
            map.put("Type", strtype);
        String straddress = 
            String.valueOf(this.address);
        if (!"-1".equals(straddress))
            map.put("Address", straddress);
        String strflags = 
            String.valueOf(this.flags);
        if (!"-1".equals(strflags))
            map.put("Flags", strflags);
        return map;
    }

    public String toString() {
        return toMap().toString();
    }

}
