/*****************************************************
 * WARNING: this file was generated by -e
 * on Wed Feb 15 18:26:49 2017.
 * Any changes made here will be LOST.
 *****************************************************/
package org.hyperic.sigar;

import java.util.HashMap;
import java.util.Map;

/**
 * DumpPidCache sigar class.
 */
public class DumpPidCache implements java.io.Serializable {

    private static final long serialVersionUID = 956L;

    public DumpPidCache() { }

    public native void gather(Sigar sigar) throws SigarException;

    /**
     * This method is not intended to be called directly.
     * use Sigar.getDumpPidCache() instead.
     * @exception SigarException on failure.
     * @see org.hyperic.sigar.Sigar#getDumpPidCache
     */
    static DumpPidCache fetch(Sigar sigar) throws SigarException {
        DumpPidCache dumpPidCache = new DumpPidCache();
        dumpPidCache.gather(sigar);
        return dumpPidCache;
    }

    long dummy = 0;

    /**
     * Get the Dummy.<p>
     * Supported Platforms: Linux, Win32, AIX, HPUX, Solaris.
     * <p>
     * @return Dummy
     */
    public long getDummy() { return dummy; }

    void copyTo(DumpPidCache copy) {
        copy.dummy = this.dummy;
    }

    public Map toMap() {
        Map map = new HashMap();
        String strdummy = 
            String.valueOf(this.dummy);
        if (!"-1".equals(strdummy))
            map.put("Dummy", strdummy);
        return map;
    }

    public String toString() {
        return toMap().toString();
    }

}
