/*****************************************************
 * WARNING: this file was generated by -e
 * on Wed Feb 15 18:26:49 2017.
 * Any changes made here will be LOST.
 *****************************************************/
package org.hyperic.sigar;

import java.util.HashMap;
import java.util.Map;

/**
 * NfsClientV2 sigar class.
 */
public class NfsClientV2 implements java.io.Serializable {

    private static final long serialVersionUID = 18751L;

    public NfsClientV2() { }

    public native void gather(Sigar sigar) throws SigarException;

    /**
     * This method is not intended to be called directly.
     * use Sigar.getNfsClientV2() instead.
     * @exception SigarException on failure.
     * @see org.hyperic.sigar.Sigar#getNfsClientV2
     */
    static NfsClientV2 fetch(Sigar sigar) throws SigarException {
        NfsClientV2 nfsClientV2 = new NfsClientV2();
        nfsClientV2.gather(sigar);
        return nfsClientV2;
    }

    long _null = 0;

    /**
     * Get the null.<p>
     * Supported Platforms: Undocumented.
     * <p>
     * @return null
     */
    public long getNull() { return _null; }
    long getattr = 0;

    /**
     * Get the getattr.<p>
     * Supported Platforms: Undocumented.
     * <p>
     * @return getattr
     */
    public long getGetattr() { return getattr; }
    long setattr = 0;

    /**
     * Get the setattr.<p>
     * Supported Platforms: Undocumented.
     * <p>
     * @return setattr
     */
    public long getSetattr() { return setattr; }
    long root = 0;

    /**
     * Get the root.<p>
     * Supported Platforms: Undocumented.
     * <p>
     * @return root
     */
    public long getRoot() { return root; }
    long lookup = 0;

    /**
     * Get the lookup.<p>
     * Supported Platforms: Undocumented.
     * <p>
     * @return lookup
     */
    public long getLookup() { return lookup; }
    long readlink = 0;

    /**
     * Get the readlink.<p>
     * Supported Platforms: Undocumented.
     * <p>
     * @return readlink
     */
    public long getReadlink() { return readlink; }
    long read = 0;

    /**
     * Get the read.<p>
     * Supported Platforms: Undocumented.
     * <p>
     * @return read
     */
    public long getRead() { return read; }
    long writecache = 0;

    /**
     * Get the writecache.<p>
     * Supported Platforms: Undocumented.
     * <p>
     * @return writecache
     */
    public long getWritecache() { return writecache; }
    long write = 0;

    /**
     * Get the write.<p>
     * Supported Platforms: Undocumented.
     * <p>
     * @return write
     */
    public long getWrite() { return write; }
    long create = 0;

    /**
     * Get the create.<p>
     * Supported Platforms: Undocumented.
     * <p>
     * @return create
     */
    public long getCreate() { return create; }
    long remove = 0;

    /**
     * Get the remove.<p>
     * Supported Platforms: Undocumented.
     * <p>
     * @return remove
     */
    public long getRemove() { return remove; }
    long rename = 0;

    /**
     * Get the rename.<p>
     * Supported Platforms: Undocumented.
     * <p>
     * @return rename
     */
    public long getRename() { return rename; }
    long link = 0;

    /**
     * Get the link.<p>
     * Supported Platforms: Undocumented.
     * <p>
     * @return link
     */
    public long getLink() { return link; }
    long symlink = 0;

    /**
     * Get the symlink.<p>
     * Supported Platforms: Undocumented.
     * <p>
     * @return symlink
     */
    public long getSymlink() { return symlink; }
    long mkdir = 0;

    /**
     * Get the mkdir.<p>
     * Supported Platforms: Undocumented.
     * <p>
     * @return mkdir
     */
    public long getMkdir() { return mkdir; }
    long rmdir = 0;

    /**
     * Get the rmdir.<p>
     * Supported Platforms: Undocumented.
     * <p>
     * @return rmdir
     */
    public long getRmdir() { return rmdir; }
    long readdir = 0;

    /**
     * Get the readdir.<p>
     * Supported Platforms: Undocumented.
     * <p>
     * @return readdir
     */
    public long getReaddir() { return readdir; }
    long fsstat = 0;

    /**
     * Get the fsstat.<p>
     * Supported Platforms: Undocumented.
     * <p>
     * @return fsstat
     */
    public long getFsstat() { return fsstat; }

    void copyTo(NfsClientV2 copy) {
        copy._null = this._null;
        copy.getattr = this.getattr;
        copy.setattr = this.setattr;
        copy.root = this.root;
        copy.lookup = this.lookup;
        copy.readlink = this.readlink;
        copy.read = this.read;
        copy.writecache = this.writecache;
        copy.write = this.write;
        copy.create = this.create;
        copy.remove = this.remove;
        copy.rename = this.rename;
        copy.link = this.link;
        copy.symlink = this.symlink;
        copy.mkdir = this.mkdir;
        copy.rmdir = this.rmdir;
        copy.readdir = this.readdir;
        copy.fsstat = this.fsstat;
    }

    public Map toMap() {
        Map map = new HashMap();
        String str_null = 
            String.valueOf(this._null);
        if (!"-1".equals(str_null))
            map.put("_null", str_null);
        String strgetattr = 
            String.valueOf(this.getattr);
        if (!"-1".equals(strgetattr))
            map.put("Getattr", strgetattr);
        String strsetattr = 
            String.valueOf(this.setattr);
        if (!"-1".equals(strsetattr))
            map.put("Setattr", strsetattr);
        String strroot = 
            String.valueOf(this.root);
        if (!"-1".equals(strroot))
            map.put("Root", strroot);
        String strlookup = 
            String.valueOf(this.lookup);
        if (!"-1".equals(strlookup))
            map.put("Lookup", strlookup);
        String strreadlink = 
            String.valueOf(this.readlink);
        if (!"-1".equals(strreadlink))
            map.put("Readlink", strreadlink);
        String strread = 
            String.valueOf(this.read);
        if (!"-1".equals(strread))
            map.put("Read", strread);
        String strwritecache = 
            String.valueOf(this.writecache);
        if (!"-1".equals(strwritecache))
            map.put("Writecache", strwritecache);
        String strwrite = 
            String.valueOf(this.write);
        if (!"-1".equals(strwrite))
            map.put("Write", strwrite);
        String strcreate = 
            String.valueOf(this.create);
        if (!"-1".equals(strcreate))
            map.put("Create", strcreate);
        String strremove = 
            String.valueOf(this.remove);
        if (!"-1".equals(strremove))
            map.put("Remove", strremove);
        String strrename = 
            String.valueOf(this.rename);
        if (!"-1".equals(strrename))
            map.put("Rename", strrename);
        String strlink = 
            String.valueOf(this.link);
        if (!"-1".equals(strlink))
            map.put("Link", strlink);
        String strsymlink = 
            String.valueOf(this.symlink);
        if (!"-1".equals(strsymlink))
            map.put("Symlink", strsymlink);
        String strmkdir = 
            String.valueOf(this.mkdir);
        if (!"-1".equals(strmkdir))
            map.put("Mkdir", strmkdir);
        String strrmdir = 
            String.valueOf(this.rmdir);
        if (!"-1".equals(strrmdir))
            map.put("Rmdir", strrmdir);
        String strreaddir = 
            String.valueOf(this.readdir);
        if (!"-1".equals(strreaddir))
            map.put("Readdir", strreaddir);
        String strfsstat = 
            String.valueOf(this.fsstat);
        if (!"-1".equals(strfsstat))
            map.put("Fsstat", strfsstat);
        return map;
    }

    public String toString() {
        return toMap().toString();
    }

}
