/*****************************************************
 * WARNING: this file was generated by -e
 * on Wed Feb 15 18:26:49 2017.
 * Any changes made here will be LOST.
 *****************************************************/
package org.hyperic.sigar;

import java.util.HashMap;
import java.util.Map;

/**
 * ProcDiskIO sigar class.
 */
public class ProcDiskIO implements java.io.Serializable {

    private static final long serialVersionUID = 4879L;

    public ProcDiskIO() { }

    public native void gather(Sigar sigar, long pid) throws SigarException;

    /**
     * This method is not intended to be called directly.
     * use Sigar.getProcDiskIO() instead.
     * @exception SigarException on failure.
     * @see org.hyperic.sigar.Sigar#getProcDiskIO
     */
    static ProcDiskIO fetch(Sigar sigar, long pid) throws SigarException {
        ProcDiskIO procDiskIO = new ProcDiskIO();
        procDiskIO.gather(sigar, pid);
        return procDiskIO;
    }

    long bytesRead = 0;

    /**
     * Get the Bytes Read.<p>
     * Supported Platforms: Linux, Win32.
     * <p>
     * @return Bytes Read
     */
    public long getBytesRead() { return bytesRead; }
    long bytesWritten = 0;

    /**
     * Get the Bytes Written.<p>
     * Supported Platforms: Linux, Win32.
     * <p>
     * @return Bytes Written
     */
    public long getBytesWritten() { return bytesWritten; }
    long bytesTotal = 0;

    /**
     * Get the Bytes Total.<p>
     * Supported Platforms: Linux, Win32, AIX, HPUX, Solaris.
     * <p>
     * @return Bytes Total
     */
    public long getBytesTotal() { return bytesTotal; }

    void copyTo(ProcDiskIO copy) {
        copy.bytesRead = this.bytesRead;
        copy.bytesWritten = this.bytesWritten;
        copy.bytesTotal = this.bytesTotal;
    }

    public Map toMap() {
        Map map = new HashMap();
        String strbytesRead = 
            String.valueOf(this.bytesRead);
        if (!"-1".equals(strbytesRead))
            map.put("BytesRead", strbytesRead);
        String strbytesWritten = 
            String.valueOf(this.bytesWritten);
        if (!"-1".equals(strbytesWritten))
            map.put("BytesWritten", strbytesWritten);
        String strbytesTotal = 
            String.valueOf(this.bytesTotal);
        if (!"-1".equals(strbytesTotal))
            map.put("BytesTotal", strbytesTotal);
        return map;
    }

    public String toString() {
        return toMap().toString();
    }

}
