# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.19)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget mongo::bson_shared mongo::bson_static)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target mongo::bson_shared
add_library(mongo::bson_shared SHARED IMPORTED)

set_target_properties(mongo::bson_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/src/libbson/src;D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libbson/src;D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libbson/src/bson"
)

# Create imported target mongo::bson_static
add_library(mongo::bson_static STATIC IMPORTED)

set_target_properties(mongo::bson_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BSON_STATIC"
  INTERFACE_INCLUDE_DIRECTORIES "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/src/libbson/src;D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libbson/src;D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libbson/src/bson"
  INTERFACE_LINK_LIBRARIES "ws2_32"
)

# Import target "mongo::bson_shared" for configuration "Debug"
set_property(TARGET mongo::bson_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(mongo::bson_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libbson/Debug/bson-1.0.lib"
  IMPORTED_LOCATION_DEBUG "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libbson/Debug/bson-1.0.dll"
  )

# Import target "mongo::bson_static" for configuration "Debug"
set_property(TARGET mongo::bson_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(mongo::bson_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libbson/Debug/bson-static-1.0.lib"
  )

# Import target "mongo::bson_shared" for configuration "Release"
set_property(TARGET mongo::bson_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(mongo::bson_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libbson/Release/bson-1.0.lib"
  IMPORTED_LOCATION_RELEASE "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libbson/Release/bson-1.0.dll"
  )

# Import target "mongo::bson_static" for configuration "Release"
set_property(TARGET mongo::bson_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(mongo::bson_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libbson/Release/bson-static-1.0.lib"
  )

# Import target "mongo::bson_shared" for configuration "MinSizeRel"
set_property(TARGET mongo::bson_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(mongo::bson_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libbson/MinSizeRel/bson-1.0.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libbson/MinSizeRel/bson-1.0.dll"
  )

# Import target "mongo::bson_static" for configuration "MinSizeRel"
set_property(TARGET mongo::bson_static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(mongo::bson_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libbson/MinSizeRel/bson-static-1.0.lib"
  )

# Import target "mongo::bson_shared" for configuration "RelWithDebInfo"
set_property(TARGET mongo::bson_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(mongo::bson_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libbson/RelWithDebInfo/bson-1.0.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libbson/RelWithDebInfo/bson-1.0.dll"
  )

# Import target "mongo::bson_static" for configuration "RelWithDebInfo"
set_property(TARGET mongo::bson_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(mongo::bson_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libbson/RelWithDebInfo/bson-static-1.0.lib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
