# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.19)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget mongo::mongoc_shared mongo::mongoc_static)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target mongo::mongoc_shared
add_library(mongo::mongoc_shared SHARED IMPORTED)

set_target_properties(mongo::mongoc_shared PROPERTIES
  INTERFACE_LINK_LIBRARIES "mongo::bson_shared"
)

# Create imported target mongo::mongoc_static
add_library(mongo::mongoc_static STATIC IMPORTED)

set_target_properties(mongo::mongoc_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "MONGOC_STATIC;BSON_STATIC"
  INTERFACE_LINK_LIBRARIES "secur32.lib;crypt32.lib;Shlwapi.lib;secur32.lib;crypt32.lib;Bcrypt.lib;Dnsapi;mongo::bson_static"
)

# Import target "mongo::mongoc_shared" for configuration "Debug"
set_property(TARGET mongo::mongoc_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(mongo::mongoc_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libmongoc/Debug/mongoc-1.0.lib"
  IMPORTED_LOCATION_DEBUG "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libmongoc/Debug/mongoc-1.0.dll"
  )

# Import target "mongo::mongoc_static" for configuration "Debug"
set_property(TARGET mongo::mongoc_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(mongo::mongoc_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libmongoc/Debug/mongoc-static-1.0.lib"
  )

# Import target "mongo::mongoc_shared" for configuration "Release"
set_property(TARGET mongo::mongoc_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(mongo::mongoc_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libmongoc/Release/mongoc-1.0.lib"
  IMPORTED_LOCATION_RELEASE "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libmongoc/Release/mongoc-1.0.dll"
  )

# Import target "mongo::mongoc_static" for configuration "Release"
set_property(TARGET mongo::mongoc_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(mongo::mongoc_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libmongoc/Release/mongoc-static-1.0.lib"
  )

# Import target "mongo::mongoc_shared" for configuration "MinSizeRel"
set_property(TARGET mongo::mongoc_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(mongo::mongoc_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libmongoc/MinSizeRel/mongoc-1.0.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libmongoc/MinSizeRel/mongoc-1.0.dll"
  )

# Import target "mongo::mongoc_static" for configuration "MinSizeRel"
set_property(TARGET mongo::mongoc_static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(mongo::mongoc_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libmongoc/MinSizeRel/mongoc-static-1.0.lib"
  )

# Import target "mongo::mongoc_shared" for configuration "RelWithDebInfo"
set_property(TARGET mongo::mongoc_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(mongo::mongoc_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libmongoc/RelWithDebInfo/mongoc-1.0.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libmongoc/RelWithDebInfo/mongoc-1.0.dll"
  )

# Import target "mongo::mongoc_static" for configuration "RelWithDebInfo"
set_property(TARGET mongo::mongoc_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(mongo::mongoc_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/workround/grypania/core/src/lib/3rd/mongo-c-driver/builds/src/libmongoc/RelWithDebInfo/mongoc-static-1.0.lib"
  )

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "mongo::bson_shared" "mongo::bson_static" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
